### PR TITLE
Add image support plus extra extension

### PR DESCRIPTION
**Pull request by Doprez**
Added an extension for ColorPicker3 to support Strides Color3 type.

Added rendering requirements to display images in ImGui using GCHandle (If there is a better way then please let me know)

This has been tested with both Diirectx and OpenGL and seems to work fine.

image

Example:
```cs
    public SceneInspectorWindow(Scene scene, IServiceRegistry services)
        : base(services)
    {
        Enabled = true;

        string imagePath = "StrideLogo.png";
        using var input = File.Open(imagePath, FileMode.Open);
        _test = Texture.Load(Game.GraphicsDevice, input);
        
        _texture = (IntPtr)GCHandle.Alloc(_test);
    }

    protected override void OnDraw(bool collapsed)
    {
        foreach (var entity in _entities)
        {
            DrawEntity(entity);
        }

        //StrideImage(_test);
        ImGui.Image(_texture, new System.Numerics.Vector2(_test.Width, _test.Height));
        ImGui.ImageButton("Test", _texture, new System.Numerics.Vector2(_test.Width, _test.Height));
    }


    protected override void Destroy()
    {
        base.Destroy();
        GCHandle.FromIntPtr(_texture).Free();
    }
```

### CODE REVIEW

**Comment by Doprez** [comment]
I was looking into a better way for users to use this feature and I think I have a simpler set up:
```cs
public static class TextureExtensions
{

    // Dictionary to hold textures
    private static readonly Dictionary<IntPtr, Texture> _textureRegistry = [];
    private static readonly Dictionary<Texture, IntPtr> _pointerRegistry = [];
    private static nint _count;

    /// <summary>
    /// Gets a pointer to the Texture and adds it to the <see cref="_textureRegistry"/> if it was not previously added.
    /// </summary>
    /// <param name="texture"></param>
    /// <returns></returns>
    public static IntPtr GetPointer(this Texture texture)
    {
        if(_pointerRegistry.TryGetValue(texture, out var pointer)) return pointer;
        _count++;
        _textureRegistry.Add(_count, texture);
        _pointerRegistry.Add(texture, _count);

        return _count;
    }

    /// <summary>
    /// Attempts to convert a pointer to a texture if its in the <see cref="_textureRegistry"/>
    /// </summary>
    /// <param name="pointer"></param>
    /// <param name="texture"></param>
    /// <returns></returns>
    public static bool TryGetTexture(this IntPtr pointer, out Texture texture)
    {
        if(_textureRegistry.TryGetValue(pointer, out texture))
        {
            return true;
        }
        return false;
    }
}
```
Extension:
```cs 
public static void Image(Texture texture)
{
    ImGui.Image(texture.GetPointer(), new Vector2(texture.Width, texture.Height));
}
```

Would this make more sense? I think this would allow the user to not have to worry about memory management if I am understanding things correctly.

**Comment by Eideren** [comment]
Hey, nice work, just a couple of comments on the architecture of this one;
The two static dictionaries used there are never cleared, them being static means that they hold onto the texture objects for the lifetime of the application.
You could just clear those collections right after `Draw()` to fix this issue.

`_textureRegistry` doesn't need to be a dictionary since the `nint` you return is just incremented on each new item. You can use a list, every time you add to the list, use the list's length-1 as the id.

As for `TextureExtensions`
- I would rather you move the methods in `TextureExtensions` into `ImGuiExtension`.
- Make them internal, if there are parts of the API where users would need this, we should cover that part for them instead of providing them this obtuse method.
- And rename `GetPointer` to something less misleading, they're not pointers to texture content after all

Thanks again for all the work you're putting in

**Comment by Doprez** [comment]
The only problem with using a list is that the index doesnt work for the first item in the list. When I return the first index of zero, ImGui will treat it as a `IntPtr.Zero` and think there is no texture needed to be drawn and draw a broken texture. The process is a bit odd since ImGui is being used as the middle man from the developer to the renderer I have to pass it through as a valid non zero "pointer" even if it is just a reference to a list or dictionary.

The other thing Im wondering about is do we want to wipe the dictionary every frame? Would it not be better to keep it in the dictionary if the user reuses the same Texture, instead of having to add and remove it every frame?

I think still implemented everything you mentioned apart from the dictionary to a list due to the previously mentioned issue.

And not a problem! I have genuinely been loving working with ImGui when I have been able away from my main PC compared to all of the other UI options. Im hoping I can finally settle on this one and stop switching frameworks lol.

**Comment by Doprez** [comment]
I guess what I could do if the list is still wanted is change the renderer to just check the zero index of the extension instead of just checking if the TextureId is zero.. but that may still be a bit weird if there is a Texture at index zero but it was actually supposed to draw the font texture?

I can play around with it tomorrow if you think this should still be changed.

**Comment by Eideren** [comment]
I think this would work in your case ?
```cs
internal static nint GetTextureKey(Texture texture)
{
    if (_pointerRegistry.TryGetValue(texture, out var key)) return key;

    _textureRegistry.Add(texture);
    nint id = (nint)_textureRegistry.Length; // Notice how the value we're assigning here, and returning below cannot be zero, it is always >= 1
    _pointerRegistry.Add(texture, id);

    return id;
}

internal static bool TryGetTexture(IntPtr key, out Texture texture)
{
    int index = ((int)key-1); // Then, following the logic above, we just have to reduce by one here to get the index
    if (index >= 0 && index < _textureRegistry.Length)
    {
        texture = _textureRegistry[index];
        return true;
    }
    return false;
}
```

> The other thing Im wondering about is do we want to wipe the dictionary every frame? Would it not be better to keep it in the dictionary if the user reuses the same Texture, instead of having to add and remove it every frame?

It would be nice to avoid paying the cost of dictionary insertions, sure, but in this case I would rather make sure we don't have out of scope or otherwise unused textures polluting the dictionary lookups. We could employ a weak table instead of a dictionary to avoid holding onto those references, and remove the clear after every draw, but I don't know how efficient those actually are compared to using a dictionary and clearing after draw.

**Comment by Doprez** [comment]
Ah that's my misunderstanding, I thought you just wanted the one list but yes this works just as well, thank you for the code.

image

> It would be nice to avoid paying the cost of dictionary insertions, sure, but in this case I would rather make sure we don't have out of scope or otherwise unused textures polluting the dictionary lookups. We could employ a weak table instead of a dictionary to avoid holding onto those references, and remove the clear after every draw, but I don't know how efficient those actually are compared to using a dictionary and clearing after draw.

That makes sense, it's definitely something we can revisit later since its internal now so it wont affect anyone. For now this is very functional and its not like we are recreating the whole texture every frame, only assigning the reference so I'm not super worried.

**Comment by Doprez** [comment]
There we go, I just needed to come at it with fresh eyes. This should be good and only uses a single list now based on your example.

**Comment by Eideren** [comment]
Looks good, thanks !

**Pull request merged**
